// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.2
// source: payment.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "payment.v1";

export interface CreatePaymentIntentRequest {
  orderId: string;
  userId: string;
  /** in smallest currency unit (cents) */
  amount: number;
  /** e.g. "usd" */
  currency: string;
  metadata: { [key: string]: string };
  /** "stripe" (default) | "paypal" */
  paymentProvider: string;
}

export interface CreatePaymentIntentRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface CreatePaymentIntentResponse {
  paymentId: string;
  clientSecret: string;
  providerPaymentId: string;
  status: string;
}

export interface CreateCheckoutSessionRequest {
  orderId: string;
  userId: string;
  amount: number;
  currency: string;
  successUrl: string;
  cancelUrl: string;
  metadata: { [key: string]: string };
  /** "stripe" (default) | "paypal" */
  paymentProvider: string;
}

export interface CreateCheckoutSessionRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface CreateCheckoutSessionResponse {
  paymentId: string;
  sessionUrl: string;
  providerSessionId: string;
  status: string;
}

export interface GetPaymentRequest {
  paymentId: string;
}

export interface GetPaymentsByOrderRequest {
  orderId: string;
  page: number;
  limit: number;
}

export interface GetPaymentsByUserRequest {
  userId: string;
  page: number;
  limit: number;
}

export interface RefundPaymentRequest {
  paymentId: string;
  amount: number;
  reason: string;
}

export interface CancelPaymentRequest {
  paymentId: string;
}

export interface PaymentResponse {
  id: string;
  orderId: string;
  userId: string;
  providerPaymentId: string;
  providerSessionId: string;
  providerRefundId: string;
  amount: number;
  refundedAmount: number;
  currency: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  paymentProvider: string;
}

export interface GetPaymentsResponse {
  payments: PaymentResponse[];
  total: number;
  page: number;
  limit: number;
}

export const PAYMENT_V1_PACKAGE_NAME = "payment.v1";

export interface PaymentServiceClient {
  createPaymentIntent(request: CreatePaymentIntentRequest): Observable<CreatePaymentIntentResponse>;

  createCheckoutSession(request: CreateCheckoutSessionRequest): Observable<CreateCheckoutSessionResponse>;

  getPayment(request: GetPaymentRequest): Observable<PaymentResponse>;

  getPaymentsByOrder(request: GetPaymentsByOrderRequest): Observable<GetPaymentsResponse>;

  getPaymentsByUser(request: GetPaymentsByUserRequest): Observable<GetPaymentsResponse>;

  refundPayment(request: RefundPaymentRequest): Observable<PaymentResponse>;

  cancelPayment(request: CancelPaymentRequest): Observable<PaymentResponse>;
}

export interface PaymentServiceController {
  createPaymentIntent(
    request: CreatePaymentIntentRequest,
  ): Promise<CreatePaymentIntentResponse> | Observable<CreatePaymentIntentResponse> | CreatePaymentIntentResponse;

  createCheckoutSession(
    request: CreateCheckoutSessionRequest,
  ): Promise<CreateCheckoutSessionResponse> | Observable<CreateCheckoutSessionResponse> | CreateCheckoutSessionResponse;

  getPayment(request: GetPaymentRequest): Promise<PaymentResponse> | Observable<PaymentResponse> | PaymentResponse;

  getPaymentsByOrder(
    request: GetPaymentsByOrderRequest,
  ): Promise<GetPaymentsResponse> | Observable<GetPaymentsResponse> | GetPaymentsResponse;

  getPaymentsByUser(
    request: GetPaymentsByUserRequest,
  ): Promise<GetPaymentsResponse> | Observable<GetPaymentsResponse> | GetPaymentsResponse;

  refundPayment(
    request: RefundPaymentRequest,
  ): Promise<PaymentResponse> | Observable<PaymentResponse> | PaymentResponse;

  cancelPayment(
    request: CancelPaymentRequest,
  ): Promise<PaymentResponse> | Observable<PaymentResponse> | PaymentResponse;
}

export function PaymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createPaymentIntent",
      "createCheckoutSession",
      "getPayment",
      "getPaymentsByOrder",
      "getPaymentsByUser",
      "refundPayment",
      "cancelPayment",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENT_SERVICE_NAME = "PaymentService";
